name = "SimulationLogs"
uuid = "e3c6736c-93d9-479d-93f3-96ff5e8836d5"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com>"]
version = "0.1.0"

[deps]
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
